#The Database ConnectioN
spring.datasource.url=${DB_URL}

#The Credentials
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

#The Builder Permission
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# --- SMTP Email Configuration ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${ADMIN_EMAIL}
spring.mail.password=${EMAIL_APP_PASSWORD}

# Required Security Protocols for Gmail
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000