package com.sanju.marks;

import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.*;

/**
 * Primary REST Controller managing all incoming HTTP requests for the Student Portal.
 * Handles unified authentication, role-based data fetching, administrative commands, 
 * and dynamic PDF generation. Configured with CORS for frontend integration.
 *
 * @author Sanjib Murmu
 * @version 1.0
 */

@RestController
@RequestMapping("/api/students")
@CrossOrigin("http://localhost:5173")
public class StudentController {

    private final StudentService service;
    private final JwtUtil jwtUtil;
    private final PdfService pdfService;

    public StudentController(StudentService service, JwtUtil jwtUtil, PdfService pdfService) {
        this.service = service;
        this.jwtUtil = jwtUtil;
        this.pdfService = pdfService;
    }

    /**
     * Retrieves aggregated academic results. 
     * Access is restricted by the Spring Security JWT filter.
     *
     * @return A list of StudentResultDTOs containing flattened grade data.
     */
    @GetMapping("/results")
    public ResponseEntity<List<StudentResultDTO>> viewResults() {
        return ResponseEntity.ok(service.getAllResults());
    }

    @PostMapping("/login")
    public ResponseEntity<?> login(
            @RequestParam String role,
            @RequestParam String username, 
            @RequestParam String password) {
        
        try {
            String authenticatedUser = service.authenticate(role, username, password);
            String token = jwtUtil.generateToken(authenticatedUser, role);
            
            return ResponseEntity.ok("Bearer " + token);
            
        } catch (IllegalArgumentException e) {
            return ResponseEntity.status(401).body(e.getMessage());
        }
    }

    /**
     * intercepts binary PDF data generated by the PdfService and formats it 
     * for direct browser download.
     *
     * @param rollNo The unique roll number of the student requesting the report.
     * @return A ResponseEntity containing the byte array of the PDF file with appropriate download headers.
     */
    @GetMapping("/report/{rollNo}")
    public ResponseEntity<byte[]> downloadReportCard(@PathVariable Long rollNo) {
        try {
            StudentResultDTO student = service.getAllResults().stream()
                .filter(s -> s.getRollNo().equals(rollNo))
                .findFirst()
                .orElseThrow(() -> new IllegalArgumentException("Student not found"));

            byte[] pdfBytes = pdfService.generateReportCard(student);

            HttpHeaders headers = new HttpHeaders();
            headers.setContentType(MediaType.APPLICATION_PDF);
            headers.setContentDispositionFormData("attachment", "report_" + rollNo + ".pdf");

            return ResponseEntity.ok()
                    .headers(headers)
                    .body(pdfBytes);
                    
        } catch (Exception e) {
            return ResponseEntity.badRequest().body(null);
        }
    }

    /**
     * Administrative endpoint to register new users into the system.
     * Hashes passwords prior to persistence and strictly enforces role assignments.
     *
     * @param username The desired login ID (Roll No or custom text).
     * @param password The raw password to be encrypted.
     * @param role The system role (e.g., "student", "teacher").
     * @param fullName The legal name of the user.
     * @param email The registered email for account recovery.
     * @return A success message, or a 400 Bad Request if the user already exists.
     */
    @PostMapping("/admin/add-user")
    public ResponseEntity<?> addUser(
            @RequestParam String username, 
            @RequestParam String password, 
            @RequestParam String role, 
            @RequestParam String fullName,
            @RequestParam(required = false, defaultValue = "user@jadavpuruniversity.in") String email) {
        try {
            String response = service.registerUser(username, password, role, fullName, email);
            return ResponseEntity.ok(response);
        } catch (IllegalArgumentException e) {
            return ResponseEntity.badRequest().body(e.getMessage());
        }
    }

    @PostMapping("/admin/add-subject")
    public ResponseEntity<?> addSubject(
            @RequestParam String subjectName, 
            @RequestParam String teacherUsername) {
        try {
            String response = service.createSubject(subjectName, teacherUsername);
            return ResponseEntity.ok(response);
        } catch (IllegalArgumentException e) {
            return ResponseEntity.badRequest().body(e.getMessage());
        }
    }


    @GetMapping("/admin/subjects")
    public ResponseEntity<?> getAllSubjects() {
        try {
            List<Map<String, String>> subjects = service.getAllSubjects();
            return ResponseEntity.ok(subjects);
        } catch (Exception e) {
            return ResponseEntity.badRequest().body("Failed to load subjects directory.");
        }
    }

    @DeleteMapping("/admin/delete-user/{username}")
    public ResponseEntity<?> deleteUser(@PathVariable String username) {
        try {
            service.deleteUser(username);
            return ResponseEntity.ok("User deleted successfully");
        } catch (Exception e) {
            return ResponseEntity.badRequest().body("Failed to delete user");
        }
    }

    @DeleteMapping("/admin/delete-subject/{subjectName}")
    public ResponseEntity<?> deleteSubject(@PathVariable String subjectName) {
        try {
            service.deleteSubject(subjectName);
            return ResponseEntity.ok("Subject deleted successfully");
        } catch (Exception e) {
            return ResponseEntity.badRequest().body("Failed to delete subject: " + e.getMessage());
        }
    }

    @PostMapping("/forgot-password")
    public ResponseEntity<?> forgotPassword(@RequestParam String username, @RequestParam String email) {
        try {
            service.forgotPassword(username, email);
            return ResponseEntity.ok("Verification code successfully dispatched!");
        } catch (IllegalArgumentException e) {
            return ResponseEntity.badRequest().body(e.getMessage());
        }
    }

    @PostMapping("/reset-password")
    public ResponseEntity<?> resetPassword(@RequestParam String token, @RequestParam String newPassword) {
        try {
            service.resetPassword(token, newPassword);
            return ResponseEntity.ok("Password updated successfully!");
        } catch (IllegalArgumentException e) {
            return ResponseEntity.badRequest().body(e.getMessage());
        }
    }
}
