services:
  - type: web
    name: university-marks-backend
    env: java
    buildCommand: "alias tput=/bin/true && mvn -B clean package -DskipTests"
    startCommand: "java -jar demo/target/demo-0.0.1-SNAPSHOT.jar"
    rootDir: demo